Repository boostcampwm-2022/web13-moyeomoyeo, pull requests merged in 2022-11, with the labels that each got.

#16 [Feature] 백엔드 환경 셋팅
  backend/.eslintrc.js
  backend/.gitignore
  backend/.prettierrc
  backend/README.md
  backend/nest-cli.json
  backend/package-lock.json
  backend/package.json
  backend/src/app.controller.spec.ts
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/app.service.ts
  backend/src/main.ts
  backend/test/app.e2e-spec.ts
  backend/test/jest-e2e.json
  backend/tsconfig.build.json
  backend/tsconfig.json
Labels: ✍ 리뷰요청, 🌿 백엔드, 🚨 우선순위-긴급

#19 [Feature] 프론트엔드 환경 세팅 1차
  .gitignore
  frontend/.eslintignore
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/.husky/pre-commit
  frontend/.husky/pre-push
  frontend/.prettierignore
  frontend/.prettierrc
  frontend/README.md
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/vercel.svg
  frontend/src/components/Title.tsx
  frontend/src/pages/_app.tsx
  frontend/src/pages/index.tsx
  frontend/src/styles/Home.module.css
  frontend/src/styles/globals.css
  frontend/tsconfig.json
Labels: 💎 프론트엔드, ✨ feature, 🚨 우선순위-긴급

#21 [Feature] 프론트엔드 환경 세팅 2차 - mantine, storybook
  frontend/.eslintrc.json
  frontend/.npmrc
  frontend/.storybook/main.ts
  frontend/.storybook/preview.tsx
  frontend/fonts.d.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/public/fonts/NanumSquareNeo-Bold.woff2
  frontend/public/fonts/NanumSquareNeo-ExtraBold.woff2
  frontend/public/fonts/NanumSquareNeo-Heavy.woff2
  frontend/public/fonts/NanumSquareNeo-Light.woff2
  frontend/public/fonts/NanumSquareNeo-Regular.woff2
  frontend/src/components/RouterTransition.tsx
  frontend/src/components/StatCounter/index.stories.tsx
  frontend/src/components/StatCounter/index.tsx
  frontend/src/pages/_app.tsx
  frontend/src/pages/_document.tsx
  frontend/src/pages/index.tsx
  frontend/src/styles/CustomFont.tsx
  frontend/src/styles/Home.module.css
  frontend/src/styles/globals.css
  frontend/src/styles/theme.ts
  frontend/src/typings/emotion.d.ts
  frontend/tsconfig.json
Labels: 💎 프론트엔드, ✨ feature, 🚨 우선순위-긴급

#20 [Feature] 백엔드 CI
  .github/workflows/backend-dev-ci.yml
  .github/workflows/slack-notification.yml
  .gitignore
  backend/.dockerignore
  backend/.eslintrc.js
  backend/dockerfile
  backend/src/main.ts
  docker-compose.yml
  frontend/package-lock.json
Labels: ✍ 리뷰요청, 🐢 우선순위-일반

#28 [Feature] 프론트엔드 CD 적용
  .github/workflows/frontend-cd.yml
  .github/workflows/frontend-ci.yml
  frontend/docker-compose.yml
  frontend/scripts/dev-deploy.sh
Labels: 💎 프론트엔드, 🚨 우선순위-긴급, 🚀 Deploy

#36 [BUGFIX] 백엔드 CD 환경변수 디버그
  .github/workflows/backend-dev-cd.yml
  backend/docker-compose.local.yml
  backend/docker-compose.yml
  backend/scripts/dev-deploy.sh
Labels: 🐞 BugFix, 🚀 Deploy

#38 [Feature] 깃헙 로그인 페이지 마크업
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/icons/logo.svg
  frontend/src/components/Footer/index.tsx
  frontend/src/components/common/PageLayout.tsx
  frontend/src/components/gitLoginButton/GitLoginButton.stories.tsx
  frontend/src/components/gitLoginButton/index.tsx
  frontend/src/pages/Login.tsx
  frontend/src/pages/My.tsx
  frontend/src/pages/Notification.tsx
  frontend/src/pages/index.tsx
  frontend/src/typings/custom.d.ts
  frontend/tsconfig.json
Labels: 💎 프론트엔드, ✨ feature, 🚨 우선순위-긴급

#43 [Feature] Header 컴포넌트 생성, 스토리북 관련 이슈들 해결
  frontend/.gitignore
  frontend/.storybook/main.ts
  frontend/.storybook/preview-head.html
  frontend/.storybook/preview.tsx
  frontend/.storybook/webpack.config.js
  frontend/docker-compose.local.yml
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/icons/logo-lg.svg
  frontend/public/icons/logo-md.svg
  frontend/src/components/Header/DetailTitle/DetailTitle.stories.tsx
  frontend/src/components/Header/DetailTitle/index.tsx
  frontend/src/components/Header/DetailTitle/styles.tsx
  frontend/src/components/Header/Header.stories.tsx
  frontend/src/components/Header/LoginButton/LoginButton.stories.tsx
  frontend/src/components/Header/LoginButton/index.tsx
  frontend/src/components/Header/RootTitle/RootTitle.stories.tsx
  frontend/src/components/Header/RootTitle/index.tsx
  frontend/src/components/Header/RootTitle/styles.tsx
  frontend/src/components/Header/UtilButton/UtilButton.stories.tsx
  frontend/src/components/Header/UtilButton/index.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/Header/styles.tsx
  frontend/src/components/StatCounter/StatCounter.stories.tsx
  frontend/src/components/StatCounter/index.tsx
  frontend/src/components/Title.tsx
  frontend/src/pages/_app.tsx
  frontend/src/pages/login.tsx
  frontend/src/styles/CommonStyles.tsx
  frontend/src/styles/GlobalStyles.tsx
  frontend/src/styles/theme.ts
  frontend/src/typings/custom.d.ts
Labels: 💎 프론트엔드, ✨ feature, 🐢 우선순위-일반

#49 [Feature] Frontend nginx 적용
  frontend/.dockerignore
  frontend/Dockerfile
  frontend/Dockerfile.development
  frontend/docker-compose.local.yml
  frontend/docker-compose.yml
  frontend/nginx.Dockerfile
  frontend/nginx.conf
  frontend/scripts/dev-env.sh
Labels: 💎 프론트엔드, ✨ feature, 🚨 우선순위-긴급, 🚀 Deploy

#47 [Feature] HTTPS 설정하기
  backend/data/nginx/nginx.conf
  backend/docker-compose.local.yml
  backend/docker-compose.yml
  backend/init-letsencrypt.sh
  backend/local/nginx.conf
  backend/nginx.Dockerfile
  backend/scripts/dev-deploy.sh
Labels: 🌿 백엔드, 🚀 Deploy, ⚙ Setting

#39 [Feature] NestJS 셋업하기
  .github/workflows/backend-dev-ci.yml
  backend/.gitignore
  backend/package-lock.json
  backend/package.json
  backend/src/app.controller.spec.ts
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/common/config/app/__test__/config.service.spec.ts
  backend/src/common/config/app/config.module.ts
  backend/src/common/config/app/config.service.ts
  backend/src/common/config/app/validate.ts
  backend/src/common/config/config-option.ts
  backend/src/common/decorator/api-error-response.decorator.ts
  backend/src/common/decorator/api-success-resposne.decorator.ts
  backend/src/common/exception/api-not-found.exception.ts
  backend/src/common/exception/bad-parameter.exception.ts
  backend/src/common/filter/all-exception.filter.ts
  backend/src/common/middleware/api-exception-logger.middleware.ts
  backend/src/common/middleware/api-success-logger.middleware.ts
  backend/src/common/response-entity.ts
  backend/src/main.ts
  backend/src/setNestApp.ts
  backend/src/setSwagger.ts
  backend/test/app.e2e-spec.ts
  backend/test/jest-e2e.json
  backend/tsconfig.json
  backend/tsconfig.paths.json
Labels: ✍ 리뷰요청, 🌿 백엔드, 🚨 우선순위-긴급

#48 [Feature] 모집 게시글 카드 컴포넌트
  frontend/src/components/ArticleTag/ArticleTag.stories.tsx
  frontend/src/components/ArticleTag/index.tsx
  frontend/src/components/GitLoginButton/GitLoginButton.stories.tsx
  frontend/src/components/GitLoginButton/index.tsx
  frontend/src/components/GroupArticleCard/GroupArticleCard.stories.tsx
  frontend/src/components/GroupArticleCard/index.tsx
  frontend/src/components/GroupArticleCard/styles.ts
  frontend/src/components/StatCounter/StatCounter.stories.tsx
  frontend/src/constants/article.ts
  frontend/src/constants/color.ts
  frontend/src/constants/dummy.ts
  frontend/src/constants/location.ts
  frontend/src/pages/login.tsx
  frontend/src/typings/types.ts
  frontend/tsconfig.json
Labels: 💎 프론트엔드, ✨ feature, 🐢 우선순위-일반

#53 [Feature] Floating Button UI 구현 + Storybook 배포 액션 추가
  .github/workflows/frontend-ci.yml
  frontend/.gitignore
  frontend/docker-compose.local.yml
  frontend/docker-compose.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/FloatingButton/FloatingButton.stories.tsx
  frontend/src/components/FloatingButton/index.tsx
  frontend/src/components/FloatingButton/styles.tsx
Labels: 💎 프론트엔드, ✨ feature, 🐢 우선순위-일반

#57 [Feature] MSW 세팅 및 무한스크롤
  .github/workflows/frontend-ci.yml
  frontend/.eslintrc.json
  frontend/package-lock.json
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/apis/test/getTestData.ts
  frontend/src/hooks/queries/useFetchTestData.ts
  frontend/src/hooks/useIntersect.ts
  frontend/src/mocks/browser.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/index.ts
  frontend/src/mocks/resolvers/test.ts
  frontend/src/mocks/server.ts
  frontend/src/pages/_app.tsx
  frontend/src/pages/test.tsx
  frontend/src/typings/types.ts
  frontend/tsconfig.json
Labels: 💎 프론트엔드, ✨ feature, 🚨 우선순위-긴급

#61 [Feature] 모집 게시글 상세보기 페이지 마크업
  frontend/src/components/ArticleTag/ArticleTag.stories.tsx
  frontend/src/components/ArticleTag/index.tsx
  frontend/src/components/GroupArticleCard/GroupArticleCard.stories.tsx
  frontend/src/components/GroupArticleCard/index.tsx
  frontend/src/constants/article.ts
  frontend/src/constants/category.ts
  frontend/src/constants/color.ts
  frontend/src/constants/dummy.ts
  frontend/src/constants/location.ts
  frontend/src/pages/article/[id].tsx
  frontend/src/pages/my.tsx
  frontend/src/pages/notification.tsx
  frontend/src/pages/test.tsx
  frontend/src/typings/types.ts
  frontend/src/utils/colors.ts
Labels: 💎 프론트엔드, ✨ feature, 🐢 우선순위-일반

#63 [Feature] 토큰 발급 및 리프레시 로직 추가
  backend/nginx.Dockerfile
  backend/package-lock.json
  backend/package.json
  backend/src/app.controller.spec.ts
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/app/user/user.entity.ts
  backend/src/common/config/jwt/__test__/config.service.spec.ts
  backend/src/common/config/jwt/config.module.ts
  backend/src/common/config/jwt/config.service.ts
  backend/src/common/config/jwt/validate.ts
  backend/src/common/decorator/jwt-auth.decorator.ts
  backend/src/common/exception/invalid-token.exception.ts
  backend/src/common/guard/jwt-auth.guard.ts
  backend/src/common/module/jwt-token/__test__/jwt-token.service.spec.ts
  backend/src/common/module/jwt-token/jwt-token.module.ts
  backend/src/common/module/jwt-token/jwt-token.service.ts
  backend/src/common/module/jwt-token/type/auth-token-payload.ts
  backend/src/common/module/jwt-token/type/token-type.ts
  backend/src/common/util/__test__/date-time.spec.ts
  backend/src/common/util/date-time.ts
  backend/src/setNestApp.ts
  backend/src/setSwagger.ts
  backend/test/app.e2e-spec.ts
Labels: 🌿 백엔드, 🚨 우선순위-긴급

#62 [Feature] Comment, CommentInput 컴포넌트 마크업
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/article/Comment/Comment.stories.tsx
  frontend/src/components/article/Comment/index.tsx
  frontend/src/components/article/Comment/styles.tsx
  frontend/src/components/article/CommentInput/CommentInput.stories.tsx
  frontend/src/components/article/CommentInput/index.tsx
  frontend/src/components/article/CommentInput/styles.tsx
  frontend/src/components/common/FloatingButton/FloatingButton.stories.tsx
  frontend/src/components/common/FloatingUtilButton/FloatingUtilButton.stories.tsx
  frontend/src/components/common/Footer/Footer.stories.tsx
  frontend/src/components/common/Header/DetailTitle/DetailTitle.stories.tsx
  frontend/src/components/common/Header/Header.stories.tsx
  frontend/src/components/common/Header/LoginButton/LoginButton.stories.tsx
  frontend/src/components/common/Header/RootTitle/RootTitle.stories.tsx
  frontend/src/components/common/Header/UtilButton/UtilButton.stories.tsx
  frontend/src/components/common/NavigationTab/NavigationTab.stories.tsx
  frontend/src/components/common/NavigationTab/index.tsx
  frontend/src/components/common/PageLayout/PageLayout.stories.tsx
  frontend/src/components/common/PageLayout/index.tsx
  frontend/src/pages/index.tsx
  frontend/src/pages/my.tsx
  frontend/src/pages/notification.tsx
  frontend/src/pages/test.tsx
  frontend/src/typings/types.ts
  frontend/src/utils/dateTime.ts
  frontend/tsconfig.json
Labels: 💎 프론트엔드, ✨ feature, 🐢 우선순위-일반

#70 [Feature] 모집 게시글 렌더링
  frontend/src/apis/test/getTestGroupArticles.ts
  frontend/src/components/common/ArticleTag/ArticleTag.stories.tsx
  frontend/src/components/common/ArticleTag/index.tsx
  frontend/src/components/common/GroupArticleCard/GroupArticleCard.stories.tsx
  frontend/src/components/common/GroupArticleCard/index.tsx
  frontend/src/components/common/GroupArticleCard/styles.ts
  frontend/src/components/common/Header/styles.tsx
  frontend/src/components/common/NavigationTab/index.tsx
  frontend/src/components/common/NoGroupMessage/NoGroupMessage.stories.tsx
  frontend/src/components/common/NoGroupMessage/index.tsx
  frontend/src/components/common/PageLayout/index.tsx
  frontend/src/components/common/RouterTransition.tsx
  frontend/src/components/common/StatCounter/StatCounter.stories.tsx
  frontend/src/components/common/StatCounter/index.tsx
  frontend/src/components/login/GitLoginButton/GitLoginButton.stories.tsx
  frontend/src/components/login/GitLoginButton/index.tsx
  frontend/src/constants/pageTitle.ts
  frontend/src/hooks/queries/useFetchGroupArticles.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/resolvers/getGroupArticles.ts
  frontend/src/pages/_app.tsx
  frontend/src/pages/article/[id].tsx
  frontend/src/pages/index.tsx
  frontend/src/pages/login.tsx
  frontend/src/pages/test.tsx
Labels: 💎 프론트엔드, ✨ feature, 🚨 우선순위-긴급

#71 [Feature] 모집 게시글 작성 페이지 & 관련 컴포넌트들 구성
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/article/ArticleEditor/ArticleEditor.stories.tsx
  frontend/src/components/article/ArticleEditor/index.tsx
  frontend/src/components/article/ImageThumbnail/ImageThumbnail.stories.tsx
  frontend/src/components/article/ImageThumbnail/index.tsx
  frontend/src/components/common/DropDown/DropDown.stories.tsx
  frontend/src/components/common/DropDown/index.tsx
  frontend/src/components/common/RouterTransition/index.tsx
  frontend/src/components/common/TextInput/TextInput.stories.tsx
  frontend/src/components/common/TextInput/index.tsx
  frontend/src/pages/article/write/index.tsx
Labels: ✍ 리뷰요청, 💎 프론트엔드, ✨ feature, 🚨 우선순위-긴급

#76 [Fix] Mantine 버전 명시 변경
  frontend/package-lock.json
  frontend/package.json
Labels: 🐞 BugFix, 💎 프론트엔드, 🐛 수정, 🚨 우선순위-긴급

#77 [Fix] 페이지 content 전체 padding 제거
  frontend/src/components/common/PageLayout/index.tsx
  frontend/src/pages/article/[id].tsx
  frontend/src/pages/index.tsx
Labels: 🐞 BugFix, 💎 프론트엔드

#84 [Fix] 로그인페이지 이슈 / 로컬 폰트 적용 이슈 해결
  frontend/src/pages/login.tsx
  frontend/src/styles/GlobalStyles.tsx
Labels: 🐞 BugFix, 💎 프론트엔드, 🚨 우선순위-긴급

#86 [Feature] 참가신청자 목록 Modal
  frontend/src/components/article/Comment/index.tsx
  frontend/src/components/article/ParticipantsModal/ParticipantItem/ParticipantItem.stories.tsx
  frontend/src/components/article/ParticipantsModal/ParticipantItem/index.tsx
  frontend/src/components/article/ParticipantsModal/ParticipantsModal.stories.tsx
  frontend/src/components/article/ParticipantsModal/index.tsx
  frontend/src/components/common/EmptyMessage/EmptyMessage.stories.tsx
  frontend/src/components/common/EmptyMessage/index.tsx
  frontend/src/components/common/Joiner/Jointer.stories.tsx
  frontend/src/components/common/Joiner/index.tsx
  frontend/src/components/common/NoGroupMessage/NoGroupMessage.stories.tsx
  frontend/src/components/common/NoGroupMessage/index.tsx
  frontend/src/constants/dummy.ts
  frontend/src/pages/article/[id].tsx
  frontend/src/pages/index.tsx
  frontend/src/typings/types.ts
Labels: 💎 프론트엔드, ✨ feature, 🐢 우선순위-일반

#69 [Feature] 이미지 업로드 API
  backend/package-lock.json
  backend/package.json
  backend/src/app.module.ts
  backend/src/app/image/dto/images-upload-response.dto.ts
  backend/src/app/image/image.controller.ts
  backend/src/app/image/image.module.ts
  backend/src/app/image/image.service.ts
  backend/src/common/config/s3/__test__/config.service.spec.ts
  backend/src/common/config/s3/config.module.ts
  backend/src/common/config/s3/config.service.ts
  backend/src/common/config/s3/validate.ts
  backend/src/common/response-entity.ts
Labels: ✍ 리뷰요청, 🌿 백엔드, ✨ feature, 🚨 우선순위-긴급

#68 [Feature] 깃허브 로그인 API 추가
  backend/package-lock.json
  backend/package.json
  backend/scripts/dev-deploy.sh
  backend/src/app.module.ts
  backend/src/app/auth/auth.controller.ts
  backend/src/app/auth/auth.module.ts
  backend/src/app/auth/auth.service.ts
  backend/src/app/auth/github-auth.guard.ts
  backend/src/app/auth/github-profile.decorator.ts
  backend/src/app/auth/github.strategy.ts
  backend/src/app/auth/type/github-profile.ts
  backend/src/app/image/image.controller.ts
  backend/src/app/user/__test__/user.fixture.ts
  backend/src/app/user/user.entity.ts
  backend/src/app/user/user.module.ts
  backend/src/app/user/user.repository.ts
  backend/src/common/config/app/config.module.ts
  backend/src/common/config/app/config.service.ts
  backend/src/common/config/app/configuration.ts
  backend/src/common/config/app/validate.ts
  backend/src/common/config/config-option.ts
  backend/src/common/config/database/mysql/config.module.ts
  backend/src/common/config/database/mysql/config.service.ts
  backend/src/common/config/database/mysql/configuration.ts
  backend/src/common/config/database/mysql/validate.ts
  backend/src/common/config/github/__test__/config.service.spec.ts
  backend/src/common/config/github/config.module.ts
  backend/src/common/config/github/config.service.ts
  backend/src/common/config/github/configuration.ts
  backend/src/common/config/jwt/config.module.ts
  backend/src/common/config/jwt/config.service.ts
  backend/src/common/config/jwt/configuration.ts
  backend/src/common/config/jwt/validate.ts
  backend/src/common/config/s3/config.module.ts
  backend/src/common/config/s3/config.service.ts
  backend/src/common/config/s3/configuration.ts
  backend/src/common/config/s3/validate.ts
  backend/src/common/config/validate.ts
  backend/src/common/guard/jwt-auth.guard.ts
  backend/src/setSwagger.ts
Labels: 🌿 백엔드, ✨ feature

#91 [FIX] 백엔드 CD 수정
  .github/workflows/backend-dev-cd.yml
  backend/.dockerignore
  backend/dev/nginx/nginx.conf
  backend/scripts/dev-deploy.sh
Labels: 🌿 백엔드, 🚀 Deploy

#92 [Feature] TypeORM 엔티티 설계
  backend/src/app/auth/auth.service.ts
  backend/src/app/comment/entity/comment.entity.ts
  backend/src/app/group-application/entity/group-application.entity.ts
  backend/src/app/group-article/entity/article.entity.ts
  backend/src/app/group-article/entity/group-article.entity.ts
  backend/src/app/group-article/entity/group-category.entity.ts
  backend/src/app/group-article/entity/group.entity.ts
  backend/src/app/notification/entity/notification-setting.entity.ts
  backend/src/app/notification/entity/notification.entity.ts
  backend/src/app/notification/entity/user-notification.entity.ts
  backend/src/app/scrap/entity/scrap.entity.ts
  backend/src/app/user/__test__/user.fixture.ts
  backend/src/app/user/entity/user.entity.ts
  backend/src/app/user/user.repository.ts
  backend/src/common/guard/jwt-auth.guard.ts
  backend/src/common/module/jwt-token/jwt-token.service.ts
Labels: 🌿 백엔드, ✨ feature, 🚨 우선순위-긴급

#93 [Feature] 모집 게시글 하단 버튼
  frontend/src/components/article/ParticipantsModal/ParticipantsModal.stories.tsx
  frontend/src/components/article/ParticipantsModal/index.tsx
  frontend/src/components/article/ParticipateButton/ApplyButton/index.tsx
  frontend/src/components/article/ParticipateButton/CancelButton/index.tsx
  frontend/src/components/article/ParticipateButton/ChatLinkButton/index.tsx
  frontend/src/components/article/ParticipateButton/ParticipateButton.stories.tsx
  frontend/src/components/article/ParticipateButton/index.tsx
  frontend/src/components/common/AlertModal/AlertModal.stories.tsx
  frontend/src/components/common/AlertModal/index.tsx
  frontend/src/constants/participateButton.ts
  frontend/src/hooks/useClipboard.ts
  frontend/src/pages/article/[id].tsx
Labels: 💎 프론트엔드, ✨ feature, 🐢 우선순위-일반

#100 [Feature] 모집 게시글 등록 API
  backend/.gitignore
  backend/package.json
  backend/sql/category.sql
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/app/group-article/constants/group-article.constants.ts
  backend/src/app/group-article/dto/group-article-register-request.dto.ts
  backend/src/app/group-article/dto/group-article-register-response.dto.ts
  backend/src/app/group-article/entity/article.entity.ts
  backend/src/app/group-article/entity/group-article.entity.ts
  backend/src/app/group-article/entity/group-category.entity.ts
  backend/src/app/group-article/entity/group.entity.ts
  backend/src/app/group-article/exception/group-category-not-found.ts
  backend/src/app/group-article/group-article.controller.ts
  backend/src/app/group-article/group-article.module.ts
  backend/src/app/group-article/group-article.service.ts
  backend/src/app/group-article/repository/article.repository.ts
  backend/src/app/group-article/repository/group-category.repository.ts
  backend/src/app/group-article/repository/group.repository.ts
  backend/src/app/image/image.controller.ts
  backend/src/app/image/image.module.ts
  backend/src/app/image/image.service.ts
  backend/src/common/config/s3/__test__/config.service.spec.ts
  backend/src/common/config/s3/config.module.ts
  backend/src/common/config/s3/config.service.ts
  backend/src/common/filter/all-exception.filter.ts
  backend/src/main.ts
  backend/src/setSwagger.ts
Labels: ✍ 리뷰요청, 🌿 백엔드, ✨ feature, 🚨 우선순위-긴급

#101 [Feature] 모집 게시글 카테고리 조회 API
  backend/scripts/dev-deploy.sh
  backend/src/app/comment/entity/comment.entity.ts
  backend/src/app/group-article/dto/get-cateogories-response.dto.ts
  backend/src/app/group-article/group-article.controller.ts
  backend/src/app/group-article/group-article.service.ts
Labels: 🌿 백엔드, ✨ feature

#104 [Feature] 프로필 페이지 마크업
  frontend/src/components/common/Profile/Profile.stories.tsx
  frontend/src/components/common/Profile/index.tsx
  frontend/src/constants/dummy.ts
  frontend/src/constants/pageTitle.ts
  frontend/src/pages/my.tsx
  frontend/src/pages/user/[id].tsx
Labels: 💎 프론트엔드, ✨ feature

#107 [Feature] 404, 500 에러 페이지
  frontend/src/components/common/ErrorMessage/ErrorMessage.stories.tsx
  frontend/src/components/common/ErrorMessage/index.tsx
  frontend/src/constants/error.ts
  frontend/src/pages/404.tsx
  frontend/src/pages/500.tsx
Labels: 💎 프론트엔드, ✨ feature

#109 [Feature] 내 정보 조회 API
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/app/group-article/exception/group-category-not-found.exception.ts
  backend/src/app/group-article/group-article.controller.ts
  backend/src/app/group-article/group-article.service.ts
  backend/src/app/myinfo/dto/myinfo-get-response.dto.ts
  backend/src/app/myinfo/myinfo.controller.ts
  backend/src/app/myinfo/myinfo.module.ts
  backend/src/app/myinfo/myinfo.service.ts
  backend/src/app/user/user.repository.ts
  backend/src/common/decorator/current-user.decorator.ts
  backend/src/setSwagger.ts
  backend/test/app.e2e-spec.ts
Labels: ✍ 리뷰요청, 🌿 백엔드, ✨ feature

#106 [Feature] 프로필 수정 페이지 마크업
  frontend/next.config.js
  frontend/src/apis/test/getTestMyData.ts
  frontend/src/hooks/queries/useFetchMyData.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/resolvers/getMyInfo.ts
  frontend/src/pages/_app.tsx
  frontend/src/pages/article/write/index.tsx
  frontend/src/pages/my/edit.tsx
Labels: 💎 프론트엔드, ✨ feature, 🐢 우선순위-일반

#111 [Feature] 모집 게시글 조회 API 제작
  backend/src/app/group-article/dto/group-article-search-result.dto.ts
  backend/src/app/group-article/dto/group-article-search-result.interface.ts
  backend/src/app/group-article/dto/search-group-articles-request.dto.ts
  backend/src/app/group-article/dto/search-group-articles-response.dto.ts
  backend/src/app/group-article/entity/article.entity.ts
  backend/src/app/group-article/entity/group-article.entity.ts
  backend/src/app/group-article/entity/group.entity.ts
  backend/src/app/group-article/group-article.controller.ts
  backend/src/app/group-article/group-article.module.ts
  backend/src/app/group-article/group-article.service.ts
  backend/src/app/group-article/repository/article.repository.ts
  backend/src/app/group-article/repository/group-article.repository.ts
  backend/src/app/image/image.module.ts
  backend/src/common/config/database/typeorm/config.service.ts
  backend/src/common/dto/image-response.dto.ts
  backend/src/common/util/__test__/page-result.spec.ts
  backend/src/common/util/page-request.ts
  backend/src/common/util/page-result.ts
  backend/src/setNestApp.ts
  backend/src/setSwagger.ts
Labels: 🌿 백엔드, ✨ feature

#113 [Feature] 닉네임 Unique 체크 API
  backend/src/app.module.ts
  backend/src/app/user/dto/nickname-unique-request.dto.ts
  backend/src/app/user/dto/nickname-unique-response.dto.ts
  backend/src/app/user/user.controller.ts
  backend/src/app/user/user.module.ts
  backend/src/app/user/user.repository.ts
  backend/src/app/user/user.service.ts
  backend/src/setSwagger.ts
Labels: ✍ 리뷰요청, 🌿 백엔드, ✨ feature

#121 [BugFix] 프론트엔드 HTTPS 배포
  .github/workflows/frontend-cd.yml
  frontend/docker-compose.yml
  frontend/scripts/dev-deploy.sh
Labels: 🐞 BugFix, ✍ 리뷰요청, 💎 프론트엔드, 🚀 Deploy

#114 [Feature] 내가 참여한 그룹 페이지 추가
  frontend/src/apis/test/getTestMyGroupArticles.ts
  frontend/src/components/common/EmptyMessage/index.tsx
  frontend/src/components/common/PageLayout/index.tsx
  frontend/src/hooks/queries/useFetchMyArticles.ts
  frontend/src/mocks/handlers.ts
  frontend/src/pages/index.tsx
  frontend/src/pages/my/index.tsx
  frontend/src/pages/my/participate.tsx
Labels: 💎 프론트엔드, ✨ feature, 🐢 우선순위-일반

#124 [BugFix] 백엔드 HTTPS 배포
  .github/workflows/backend-dev-cd.yml
  backend/dev/nginx/nginx.conf
  frontend/dev/nginx/nginx.conf
Labels: 🐞 BugFix, ✍ 리뷰요청, 🌿 백엔드, 🚨 우선순위-긴급, 🚀 Deploy

#127 [Feature] 쿠키 옵션 설정 수정
  backend/src/app.module.ts
  backend/src/app/auth/auth.controller.ts
  backend/src/app/auth/auth.module.ts
  backend/src/app/group-article/group-article.controller.ts
  backend/src/app/group-article/group-article.module.ts
  backend/src/app/myinfo/myinfo.module.ts
  backend/src/app/user/user.module.ts
  backend/src/common/config/cookie/config.module.ts
  backend/src/common/config/cookie/config.service.ts
  backend/src/common/config/cookie/configuration.ts
  backend/src/common/guard/jwt-auth.guard.ts
  backend/src/common/module/jwt-token/jwt-token.module.ts
Labels: 🌿 백엔드, ✨ feature

#132 [Fix] 모집 게시글 작성 API 수정
  backend/src/app/group-article/constants/group-article.constants.ts
  backend/src/app/group-article/dto/group-article-register-request.dto.ts
  backend/src/app/group-article/entity/article.entity.ts
  backend/src/app/group-article/entity/group-article.entity.ts
  backend/src/app/group-article/entity/group.entity.ts
  backend/src/app/group-article/group-article.controller.ts
  backend/src/app/group-article/group-article.service.ts
  backend/src/app/group-article/repository/group-article.repository.ts
  backend/src/setSwagger.ts
Labels: 🐞 BugFix, 🌿 백엔드

#134 [Feature] 프로필 수정 API
  backend/src/app/myinfo/dto/profile-modifying-request.dto.ts
  backend/src/app/myinfo/exception/username-duplicate.exception.ts
  backend/src/app/myinfo/myinfo.controller.ts
  backend/src/app/myinfo/myinfo.service.ts
  backend/src/app/user/entity/user.entity.ts
  backend/src/app/user/user.repository.ts
  backend/src/common/decorator/api-success-resposne.decorator.ts
  backend/src/common/guard/jwt-auth.guard.ts
  backend/src/common/response-entity.ts
Labels: ✍ 리뷰요청, 🌿 백엔드, ✨ feature, 🚨 우선순위-긴급

#133 [Feature] 모집 게시글 삭제 API
  backend/src/app/group-article/entity/group-article.entity.ts
  backend/src/app/group-article/exception/group-article-not-found.exception.ts
  backend/src/app/group-article/exception/not-author.exception.ts
  backend/src/app/group-article/group-article.controller.ts
  backend/src/app/group-article/group-article.service.ts
Labels: 🌿 백엔드, ✨ feature

#140 [Feature] 이미지 업로드 Swagger 보충
  backend/src/app/image/image.controller.ts
Labels: 🌿 백엔드, ✨ feature, 🚨 우선순위-긴급

#135 [Feature] 로그인 API 연동 및 리다이렉션 로직 생성
  .github/workflows/frontend-cd.yml
  .github/workflows/frontend-ci.yml
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/.storybook/preview.tsx
  frontend/next.config.js
  frontend/package.json
  frontend/scripts/dev-deploy.sh
  frontend/src/apis/test/getTestMyData.ts
  frontend/src/components/common/FloatingUtilButton/FloatingUtilButton.stories.tsx
  frontend/src/components/common/FloatingUtilButton/index.tsx
  frontend/src/components/common/Header/Header.stories.tsx
  frontend/src/components/common/Header/UserLoginItem/index.tsx
  frontend/src/components/common/LoginRedirect/index.tsx
  frontend/src/components/common/PageLayout/PageLayout.stories.tsx
  frontend/src/components/common/PageLayout/index.tsx
  frontend/src/components/common/Profile/index.tsx
  frontend/src/components/login/GitLoginButton/index.tsx
  frontend/src/hooks/queries/useFetchMyData.ts
  frontend/src/hooks/queries/useFetchMyInfo.ts
  frontend/src/pages/_app.tsx
  frontend/src/pages/article/[id].tsx
  frontend/src/pages/index.tsx
  frontend/src/pages/login.tsx
  frontend/src/pages/my/edit.tsx
  frontend/src/pages/my/index.tsx
  frontend/src/typings/types.ts
Labels: 💎 프론트엔드, ✨ feature, 🚨 우선순위-긴급

#139 [Feature] 모집 게시글 상세조회 API 제작
  backend/src/app/group-article/dto/author.dto.ts
  backend/src/app/group-article/dto/get-group-article-detail-response.dto.ts
  backend/src/app/group-article/dto/group-article-detail.interface.ts
  backend/src/app/group-article/dto/group-article-search-result.dto.ts
  backend/src/app/group-article/group-article.controller.ts
  backend/src/app/group-article/group-article.service.ts
  backend/src/app/group-article/repository/group-article.repository.ts
  backend/src/common/dto/image-response.dto.ts
Labels: 🌿 백엔드, ✨ feature

#145 [Feature] Dockerfile에 환경 변수 주입
  .github/workflows/frontend-cd.yml
  .github/workflows/frontend-ci.yml
  frontend/Dockerfile
  frontend/scripts/dev-deploy.sh
  frontend/src/components/login/GitLoginButton/index.tsx
Labels: 🐞 BugFix, 💎 프론트엔드, 🚨 우선순위-긴급

#143 [Feature] 모집 신청하기 API
  backend/sql/category.sql
  backend/src/app.module.ts
  backend/src/app/group-application/dto/attend-group-request.dto.ts
  backend/src/app/group-application/dto/attend-group-response.dto.ts
  backend/src/app/group-application/entity/group-application.entity.ts
  backend/src/app/group-application/exception/cannot-applicate.exception.ts
  backend/src/app/group-application/exception/duplicate-application.exception.ts
  backend/src/app/group-application/exception/group-not-found.exception.ts
  backend/src/app/group-application/group-application.controller.ts
  backend/src/app/group-application/group-application.module.ts
  backend/src/app/group-application/group-application.repository.ts
  backend/src/app/group-application/group-application.service.ts
  backend/src/app/group-application/type/group-application-status.transformer.ts
  backend/src/app/group-article/group-article.module.ts
  backend/src/app/group-article/repository/group-article.repository.ts
  backend/src/setSwagger.ts
Labels: ✍ 리뷰요청, 🌿 백엔드, ✨ feature

#141 [Feature] 클라이언트 에러 및 API 에러 처리 로직 구상
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/article/ArticleList/index.tsx
  frontend/src/components/common/ErrorBoundary/ApiErrorBoundary.tsx
  frontend/src/components/common/ErrorBoundary/AuthError.ts
  frontend/src/components/common/ErrorBoundary/AuthErrorBoundary.tsx
  frontend/src/components/common/ErrorBoundary/ErrorBoundary.tsx
  frontend/src/components/common/ErrorMessage/index.tsx
  frontend/src/components/common/RedirectHomeModal/index.tsx
  frontend/src/hooks/queries/useFetchGroupArticles.ts
  frontend/src/hooks/useAuthMutation.ts
  frontend/src/hooks/useAuthQuery.ts
  frontend/src/hooks/useGeneralQuery.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/resolvers/postTest.ts
  frontend/src/pages/_app.tsx
  frontend/src/pages/index.tsx
Labels: 💎 프론트엔드, ✨ feature, 🚨 우선순위-긴급

#152 [Feature] credential 옵션 추가
  .github/workflows/frontend-cd.yml
  .github/workflows/frontend-ci.yml
  backend/.gitignore
  backend/src/setNestApp.ts
  frontend/next.config.js
  frontend/scripts/dev-deploy.sh
  frontend/src/components/login/GitLoginButton/index.tsx
  frontend/src/hooks/queries/useFetchMyInfo.ts
Labels: 🐞 BugFix, 🌿 백엔드, 💎 프론트엔드, 🐛 수정, 🚨 우선순위-긴급

#153 [Feature] 모임 신청 여부 조회 API
  backend/src/app/group-application/dto/check-joining-group-response.dto.ts
  backend/src/app/group-application/dto/group-application-request.dto.ts
  backend/src/app/group-application/entity/group-application.entity.ts
  backend/src/app/group-application/group-application.controller.ts
  backend/src/app/group-application/group-application.service.ts
  backend/src/app/group-article/entity/group-article.entity.ts
Labels: ✍ 리뷰요청, 🌿 백엔드, ✨ feature, 🚨 우선순위-긴급

#146 [Feature] 모집 중단 API 추가
  backend/src/app/group-article/dto/get-group-article-detail-response.dto.ts
  backend/src/app/group-article/dto/group-article-register-request.dto.ts
  backend/src/app/group-article/dto/group-article-search-result.dto.ts
  backend/src/app/group-article/entity/group-article.entity.ts
  backend/src/app/group-article/entity/group.entity.ts
  backend/src/app/group-article/group-article.controller.ts
  backend/src/app/group-article/group-article.service.ts
  backend/src/app/group-article/repository/group-category.repository.ts
Labels: 🌿 백엔드, ✨ feature
