Repository boostcampwm-2022/web13-moyeomoyeo, pull requests merged in 2022-12, with the labels that each got.

#163 [BUGFIX] 이미지 업로드 예외처리
  backend/src/app/image/image.controller.ts
  backend/src/app/image/image.service.ts
Labels: 🐞 BugFix, 🌿 백엔드, 🚨 우선순위-긴급

#164 [Feature] 모집 게시글 채팅방 url 조회 API 추가
  backend/src/app/group-article/dto/get-group-chat-url-response.dto.ts
  backend/src/app/group-article/exception/not-participant.exception.ts
  backend/src/app/group-article/exception/not-success-group.exception.ts
  backend/src/app/group-article/group-article.controller.ts
  backend/src/app/group-article/group-article.service.ts
  backend/src/common/config/database/typeorm/config.service.ts
  backend/src/common/guard/jwt-auth.guard.ts
Labels: 🌿 백엔드, ✨ feature

#165 [Feature] 게시글 조회 API 연결
  frontend/src/apis/group-articles/getGroupArticles.ts
  frontend/src/apis/group-articles/getSpecificArticle.ts
  frontend/src/apis/test/getTestData.ts
  frontend/src/apis/test/getTestGroupArticles.ts
  frontend/src/apis/test/getTestMyGroupArticles.ts
  frontend/src/components/article/ArticleList/index.tsx
  frontend/src/components/common/GroupArticleCard/index.tsx
  frontend/src/constants/color.ts
  frontend/src/constants/dummy.ts
  frontend/src/hooks/queries/useFetchArticle.ts
  frontend/src/hooks/queries/useFetchGroupArticles.ts
  frontend/src/mocks/handlers.ts
  frontend/src/pages/_app.tsx
  frontend/src/pages/article/[id].tsx
  frontend/src/pages/index.tsx
  frontend/src/typings/types.ts
  frontend/src/utils/colors.ts
Labels: 💎 프론트엔드, ✨ feature

#160 [Feature] 게시글 등록 API 연동 및 이미지 업로드 공통 로직
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/article/ArticleEditor/index.tsx
  frontend/src/components/common/LoginRedirect/index.tsx
  frontend/src/components/common/RouterTransition.tsx
  frontend/src/components/common/RouterTransition/index.tsx
  frontend/src/hooks/queries/useFetchMyInfo.ts
  frontend/src/hooks/useImageUpload.ts
  frontend/src/pages/_app.tsx
  frontend/src/pages/article/write/index.tsx
  frontend/src/styles/CommonStyles.tsx
  frontend/src/typings/types.ts
  frontend/src/utils/commonAxios.ts
Labels: 💎 프론트엔드, ✨ feature, 🚨 우선순위-긴급

#172 [Feature] 명세 변경으로 인한 신청 여부 조회 API 수정
  backend/src/app/group-application/group-application.controller.ts
Labels: ✍ 리뷰요청, 🌿 백엔드, ✨ feature, 🚨 우선순위-긴급

#170 [Feature] 유저 프로필 조회 API 연결
  frontend/src/hooks/queries/useFetchProfile.ts
  frontend/src/pages/user/[id].tsx
Labels: 💎 프론트엔드, ✨ feature

#174 [BUGFIX] userName 중복 확인 API
  backend/src/app/user/user.controller.ts
  backend/src/app/user/user.repository.ts
  backend/src/app/user/user.service.ts
Labels: 🐞 BugFix, 🌿 백엔드, 🚨 우선순위-긴급

#176 [Feature] 프로필 수정 기능 추가
  frontend/src/components/article/ArticleEditor/index.tsx
  frontend/src/components/common/ErrorBoundary/ApiErrorBoundary.tsx
  frontend/src/components/common/LoginRedirect/index.tsx
  frontend/src/hooks/queries/useEditMyProfile.ts
  frontend/src/hooks/useAsyncError.ts
  frontend/src/hooks/useAuthMutation.ts
  frontend/src/pages/article/write/index.tsx
  frontend/src/pages/my/edit.tsx
  frontend/src/typings/types.ts
  frontend/src/utils/toast.tsx
  frontend/src/utils/uploadImage.ts
Labels: 💎 프론트엔드, ✨ feature, 🐢 우선순위-일반

#181 [BUGFIX] 이미지 url이 제대로 전달되지 않는 문제 수정
  backend/src/app/group-article/dto/get-group-article-detail-response.dto.ts
  backend/src/app/group-article/dto/group-article-register-request.dto.ts
  backend/src/app/group-article/dto/group-article-search-result.dto.ts
  backend/src/app/group-article/group-article.controller.ts
  backend/src/app/group-article/group-article.module.ts
  backend/src/app/image/image.service.ts
Labels: 🐞 BugFix, 🌿 백엔드

#186 [BUGFIX] 게시글 썸네일 업로드시 url을 전송
  frontend/src/pages/article/write/index.tsx
Labels: 🐞 BugFix, 💎 프론트엔드, 🚨 우선순위-긴급

#175 [Feature] 사용자 알림 설정 상태 수정 및 조회 API
  backend/src/app.module.ts
  backend/src/app/auth/auth.service.ts
  backend/src/app/notification/constants/notification.constants.ts
  backend/src/app/notification/dto/get-notification-settings-response.dto.ts
  backend/src/app/notification/dto/patch-notification-setting-request.dto.ts
  backend/src/app/notification/entity/notification-setting.entity.ts
  backend/src/app/notification/exception/not-accessible.exception.ts
  backend/src/app/notification/exception/notification-setting-not-found.exception.ts
  backend/src/app/notification/notification.controller.ts
  backend/src/app/notification/notification.module.ts
  backend/src/app/notification/notification.service.ts
  backend/src/app/notification/repository/notification-setting.repository.ts
  backend/src/setSwagger.ts
Labels: 🌿 백엔드, ✨ feature

#195 [Feature] 모집 게시글 댓글 작성 API
  backend/src/app.module.ts
  backend/src/app/comment/comment.controller.ts
  backend/src/app/comment/comment.module.ts
  backend/src/app/comment/comment.repository.ts
  backend/src/app/comment/comment.service.ts
  backend/src/app/comment/dto/comment-writing-request.dto.ts
  backend/src/app/comment/dto/comment-writing-response.dto.ts
  backend/src/app/comment/entity/comment.entity.ts
  backend/src/app/comment/exception/group-not-found.exception.ts
  backend/src/app/group-application/group-application.service.ts
  backend/src/setSwagger.ts
Labels: ✍ 리뷰요청, 🌿 백엔드, ✨ feature

#188 [Feature] 내가 작성한 모집 게시글 목록 조회
  backend/src/app/group-article/group-article.controller.ts
  backend/src/app/group-article/repository/group-article.repository.ts
  backend/src/common/config/database/typeorm/config.service.ts
Labels: 🌿 백엔드, ✨ feature

#193 [Feature] 알림 컴포넌트, 페이지 마크업
  frontend/src/components/common/EmptyMessage/index.tsx
  frontend/src/components/notification/NotificationIcon/index.tsx
  frontend/src/components/notification/NotificationItem/NotificationItem.stories.tsx
  frontend/src/components/notification/NotificationItem/index.tsx
  frontend/src/constants/notification.ts
  frontend/src/pages/notification.tsx
  frontend/src/typings/types.ts
Labels: 💎 프론트엔드, ✨ feature, 🐢 우선순위-일반

#198 [BUGFIX] 게시글 상세 조회시 NaN 요청 보내는 문제 해결
  frontend/src/components/common/ArticleLoading/index.tsx
  frontend/src/hooks/useAuthQuery.ts
  frontend/src/hooks/useGeneralQuery.ts
  frontend/src/pages/article/[id].tsx
  frontend/src/pages/user/[id].tsx
Labels: 🐞 BugFix, 💎 프론트엔드

#197 [Feature] 모집 게시글 댓글 삭제 API
  backend/src/app/comment/comment.controller.ts
  backend/src/app/comment/comment.repository.ts
  backend/src/app/comment/comment.service.ts
  backend/src/app/comment/entity/comment.entity.ts
  backend/src/app/comment/exception/comment-not-found.exception.ts
  backend/src/app/comment/exception/not-author.exception.ts
  backend/src/app/myinfo/dto/profile-modifying-request.dto.ts
Labels: ✍ 리뷰요청, 🌿 백엔드, ✨ feature

#211 [Feature] 채팅 url을 chatUrl로 통일
  backend/src/app/group-article/dto/get-group-chat-url-response.dto.ts
  backend/src/app/group-article/dto/get-my-group-article-response.dto.ts
Labels: 🌿 백엔드, ✨ feature

#201 [Feature] 내가 작성한 그룹
  .github/workflows/frontend-ci.yml
  frontend/src/apis/group-articles/getGroupArticles.ts
  frontend/src/apis/group-articles/getSpecificArticle.ts
  frontend/src/constants/dummy.ts
  frontend/src/hooks/queries/useFetchArticle.ts
  frontend/src/hooks/queries/useFetchGroupArticles.ts
  frontend/src/hooks/queries/useFetchMyWriteArticles.ts
  frontend/src/hooks/queries/useFetchProfile.ts
  frontend/src/hooks/queries/useFetchTestData.ts
  frontend/src/hooks/useAuthInfiniteQuery.ts
  frontend/src/pages/article/[id].tsx
  frontend/src/pages/index.tsx
  frontend/src/pages/my/index.tsx
  frontend/src/pages/my/write.tsx
  frontend/src/typings/types.ts
Labels: 💎 프론트엔드, ✨ feature, 🐢 우선순위-일반

#205 [Feature] 프론트 API 에러 처리 보완
  frontend/src/components/common/ErrorBoundary/ApiErrorBoundary.tsx
  frontend/src/components/common/ErrorBoundary/AuthErrorBoundary.tsx
  frontend/src/hooks/useAsyncError.ts
  frontend/src/hooks/useAuthInfiniteQuery.ts
  frontend/src/hooks/useAuthMutation.ts
  frontend/src/hooks/useAuthQuery.ts
  frontend/src/hooks/useGeneralQuery.ts
  frontend/src/utils/errors/AuthError.ts
  frontend/src/utils/errors/GetError.ts
  frontend/src/utils/errors/RequestError.ts
Labels: 💎 프론트엔드, ✨ feature

#204 [Feature] 모집 게시글 댓글 조회 API
  backend/src/app/comment/comment.controller.ts
  backend/src/app/comment/comment.module.ts
  backend/src/app/comment/comment.repository.ts
  backend/src/app/comment/comment.service.ts
  backend/src/app/comment/dto/comment-response.dto.ts
  backend/src/app/comment/dto/get-all-comment-query-request.dto.ts
  backend/src/app/comment/dto/group-article-comment-get-response.dto.ts
  backend/src/app/group-application/exception/not-author.exception.ts
  backend/src/app/group-application/group-application.service.ts
Labels: ✍ 리뷰요청, 🌿 백엔드, ✨ feature

#215 [Feature] 이미지 blur url 전달하기
  backend/package-lock.json
  backend/package.json
  backend/src/app/group-article/dto/group-article-search-result.dto.ts
  backend/src/app/group-article/group-article.controller.ts
  backend/src/app/group-article/my-group-article.controller.ts
  backend/src/common/dto/image-response.dto.ts
  backend/src/common/dto/image-with-blur-response.dto.ts
Labels: 🌿 백엔드, ✨ feature

#213 [Feature] 게시글 상세 Menu버튼 관련 기능
  frontend/src/components/article/ArticlePostInput/index.tsx
  frontend/src/components/article/MenuButton/index.tsx
  frontend/src/components/common/ConfirmModal/ConfirmModal.stories.tsx
  frontend/src/components/common/ConfirmModal/index.tsx
  frontend/src/hooks/queries/useCancelRecruitment.ts
  frontend/src/hooks/queries/useCompleteRecruitment.ts
  frontend/src/hooks/queries/useDeleteArticle.ts
  frontend/src/hooks/queries/useEditMyArticle.ts
  frontend/src/hooks/queries/useFetchChatUrl.ts
  frontend/src/hooks/queries/useFetchMyArticle.ts
  frontend/src/pages/article/[id].tsx
  frontend/src/pages/article/edit/[id].tsx
  frontend/src/pages/article/write/index.tsx
  frontend/src/pages/my/edit.tsx
  frontend/src/typings/types.ts
  frontend/src/utils/toast.tsx
Labels: 💎 프론트엔드, ✨ feature

#220 [Feature] 이미지 압축, 이미지 에러 대응, 아바타 최적화
  frontend/package-lock.json
  frontend/package.json
  frontend/public/avatar.jpg
  frontend/public/default.jpg
  frontend/src/components/article/Comment/index.tsx
  frontend/src/components/article/ImageThumbnail/index.tsx
  frontend/src/components/article/ParticipantsModal/ParticipantItem/index.tsx
  frontend/src/components/common/Avatar/index.tsx
  frontend/src/components/common/GroupArticleCard/index.tsx
  frontend/src/components/common/Header/UserLoginItem/index.tsx
  frontend/src/components/common/Image/index.tsx
  frontend/src/components/common/Profile/index.tsx
  frontend/src/constants/dummy.ts
  frontend/src/hooks/queries/useFetchMyWriteArticles.ts
  frontend/src/pages/article/[id].tsx
  frontend/src/pages/article/write/index.tsx
  frontend/src/pages/my/edit.tsx
  frontend/src/typings/types.ts
  frontend/src/utils/uploadImage.ts
Labels: 💎 프론트엔드, ✨ feature, 🐢 우선순위-일반

#216 [Feature] 내가 참가한 모임 조회 API
  backend/src/app/group-application/dto/group-article-response.dto.ts
  backend/src/app/group-application/dto/my-group-request.dto.ts
  backend/src/app/group-application/dto/my-group-response.dto.ts
  backend/src/app/group-application/dto/my-group-result.interface.ts
  backend/src/app/group-application/group-application.controller.ts
  backend/src/app/group-application/group-application.repository.ts
  backend/src/app/group-application/group-application.service.ts
Labels: ✍ 리뷰요청, 🌿 백엔드, ✨ feature

#223 [Feature] 메인 페이지 SSR
  frontend/src/hooks/queries/useFetchGroupArticles.ts
  frontend/src/pages/_app.tsx
  frontend/src/pages/index.tsx
Labels: 💎 프론트엔드, ✨ feature

#228 [BUGFIX] 헤더상단 드랍다운 버그 해결
  frontend/src/components/common/Avatar/index.tsx
Labels: 🐞 BugFix, 💎 프론트엔드, 🚨 우선순위-긴급

#231 [Feature] GroupArticle 썸네일에 blur 처리
  frontend/src/components/common/GroupArticleCard/index.tsx
  frontend/src/hooks/queries/useFetchGroupArticles.ts
Labels: 💎 프론트엔드, ✨ feature, 🐢 우선순위-일반

#235 [Feature] 모집 API 예외처리 추가 및 알림달기
  backend/src/app/group-application/exception/closed-group.exception.ts
  backend/src/app/group-application/group-application.controller.ts
  backend/src/app/group-application/group-application.repository.ts
  backend/src/app/group-application/group-application.service.ts
Labels: ✍ 리뷰요청, 🌿 백엔드, ✨ feature

#227 [Feature] 알림 삭제 API 추가
  backend/src/app/notification/entity/user-notification.entity.ts
  backend/src/app/notification/exception/user-notification-not-found.exception.ts
  backend/src/app/notification/notification.controller.ts
  backend/src/app/notification/notification.service.ts
Labels: 🌿 백엔드, ✨ feature

#234 [Feature] 신청자 목록 조회
  frontend/src/components/article/ParticipantsModal/ParticipantItem/index.tsx
  frontend/src/components/article/ParticipantsModal/index.tsx
  frontend/src/components/article/ParticipateButton/ApplyButton/index.tsx
  frontend/src/components/article/ParticipateButton/CancelButton/index.tsx
  frontend/src/constants/dummy.ts
  frontend/src/hooks/queries/useApplyGroup.ts
  frontend/src/hooks/queries/useCancelApplication.ts
  frontend/src/hooks/queries/useFetchApplicationStatus.ts
  frontend/src/hooks/queries/useFetchArticle.ts
  frontend/src/hooks/queries/useFetchParticipants.ts
  frontend/src/pages/article/[id].tsx
  frontend/src/pages/user/[id].tsx
  frontend/src/typings/types.ts
Labels: 💎 프론트엔드, ✨ feature

#247 [Feature] 로그아웃 API
  backend/src/app/auth/auth.controller.ts
  backend/src/app/group-application/group-application.service.ts
Labels: ✍ 리뷰요청, 🌿 백엔드, ✨ feature, 🚨 우선순위-긴급

#244 [Feature] 댓글 추가, 삭제, 조회 로직
  frontend/src/components/article/Comment/Comment.stories.tsx
  frontend/src/components/article/Comment/index.tsx
  frontend/src/components/article/Comment/styles.tsx
  frontend/src/components/article/CommentInput/index.tsx
  frontend/src/components/article/CommentInput/styles.tsx
  frontend/src/components/common/Avatar/index.tsx
  frontend/src/components/common/FloatingButton/index.tsx
  frontend/src/components/common/Header/UserLoginItem/index.tsx
  frontend/src/components/common/Profile/index.tsx
  frontend/src/hooks/queries/useAddComment.ts
  frontend/src/hooks/queries/useDeleteComment.ts
  frontend/src/hooks/queries/useFetchComments.ts
  frontend/src/hooks/queries/useFetchGroupArticles.ts
  frontend/src/hooks/useAuthInfiniteQuery.ts
  frontend/src/pages/article/[id].tsx
  frontend/src/pages/index.tsx
  frontend/src/typings/types.ts
Labels: 💎 프론트엔드, ✨ feature, 🐢 우선순위-일반

#253 [Feature] 내가 참여한 모임 thumbnail response 수정
  backend/package-lock.json
  backend/package.json
  backend/src/app/group-application/dto/group-article-response.dto.ts
  backend/src/app/group-application/group-application.service.ts
Labels: 🌿 백엔드, ✨ feature

#251 [Feature] 알림 조회/삭제
  frontend/src/components/notification/NotificationIcon/index.tsx
  frontend/src/components/notification/NotificationItem/NotificationItem.stories.tsx
  frontend/src/components/notification/NotificationItem/index.tsx
  frontend/src/constants/article.ts
  frontend/src/constants/notification.ts
  frontend/src/hooks/queries/useDeleteNotification.ts
  frontend/src/hooks/queries/useFetchNotifications.ts
  frontend/src/pages/notification.tsx
  frontend/src/typings/types.ts
Labels: 💎 프론트엔드, ✨ feature

#256 [BUGFIX] 내가 작성한 댓글에 대해 알림이 오는 문제
  backend/src/app/comment/comment.repository.ts
  backend/src/app/notification/entity/notification.entity.ts
  backend/src/app/notification/notification.listener.ts
  backend/src/app/notification/repository/user-notification.repository.ts
Labels: 🐞 BugFix, ✍ 리뷰요청, 🌿 백엔드, 🚨 우선순위-긴급

#259 [BUGFIX] Group Not Found Exception 서버 에러
  backend/src/app/comment/comment.controller.ts
  backend/src/app/comment/comment.service.ts
  backend/src/app/comment/dto/comment-writing-response.dto.ts
Labels: 🐞 BugFix, ✍ 리뷰요청, 🌿 백엔드, 🚨 우선순위-긴급

#261 [Feature] 에러 처리 - GET 에러 발생 modal
  frontend/src/components/common/ErrorBoundary/ApiErrorBoundary.tsx
  frontend/src/components/common/ErrorMessage/index.tsx
  frontend/src/hooks/useAuthInfiniteQuery.ts
  frontend/src/pages/_app.tsx
Labels: 💎 프론트엔드, ✨ feature

#268 [BUGFIX] 참여한 모집 게시글 목록 조회 500에러 발생
  backend/src/app/group-application/dto/group-article-response.dto.ts
  backend/src/app/group-application/group-application.repository.ts
  backend/src/app/group-article/__test__/group-article.fixture.ts
Labels: 🐞 BugFix, ✍ 리뷰요청, 🌿 백엔드, 🚨 우선순위-긴급

#271 [Feature] limit, offset 페이지네이션 방식에서 전체 개수 전달하기
  backend/src/common/util/page-result.ts
Labels: 🌿 백엔드, ✨ feature

#269 [BUGFIX] 프로필 이미지 변경 대응
  frontend/src/components/common/Image/index.tsx
Labels: 🐞 BugFix, 💎 프론트엔드, 🚨 우선순위-긴급

#273 [Bugfix] 오픈채팅방 링크버튼 대신 모집마감 버튼이 뜨는 버그 해결
  frontend/src/pages/article/[id].tsx
Labels: 🐞 BugFix, 💎 프론트엔드, 🚨 우선순위-긴급

#274 [Feature] Group Application - 참가 신청 API Test 작성
  backend/src/app/group-application/__test__/group-application.fixture.ts
  backend/src/app/group-article/__test__/group-article.fixture.ts
  backend/src/app/group-article/__test__/group.fixture.ts
  backend/test/group-application.e2e-spec.ts
Labels: ✍ 리뷰요청, 🌿 백엔드, ✨ feature

#278 [Feature] 로딩 스켈레톤 딜레이 적용
  frontend/src/components/common/ArticleListLoading/index.tsx
  frontend/src/components/common/ArticleViewLoading/index.tsx
  frontend/src/hooks/useDeferredResponse.ts
Labels: 💎 프론트엔드, ✨ feature

#283 [Feature] 플로팅 화면 위치를 모바일 화면 안으로 넣기
  frontend/src/components/common/FloatingButton/styles.tsx
Labels: ✍ 리뷰요청, 💎 프론트엔드, 🐢 우선순위-일반

#280 [Feature] 게시물 작성자에게도 댓글 알림이 가도록 설정
  backend/src/app/notification/notification.listener.ts
Labels: ✍ 리뷰요청, 🌿 백엔드, ✨ feature

#281 [BUGFIX] 모집완료시 마지막 참가신청자에게 알림이 가지 않는 문제
  backend/src/app/group-application/group-application.service.ts
Labels: 🐞 BugFix, ✍ 리뷰요청, 🌿 백엔드

#290 [Feature] Group Application - 참가 신청자 조회 API Test
  backend/test/group-application.e2e-spec.ts
Labels: ✍ 리뷰요청, 🌿 백엔드, ✨ feature

#286 [Feature] 로그아웃 연동 및 추가 이미지 최적화, Favicon + OG 변경
  frontend/package-lock.json
  frontend/package.json
  frontend/public/android-icon-144x144.png
  frontend/public/android-icon-192x192.png
  frontend/public/android-icon-36x36.png
  frontend/public/android-icon-48x48.png
  frontend/public/android-icon-72x72.png
  frontend/public/android-icon-96x96.png
  frontend/public/apple-icon-114x114.png
  frontend/public/apple-icon-120x120.png
  frontend/public/apple-icon-144x144.png
  frontend/public/apple-icon-152x152.png
  frontend/public/apple-icon-180x180.png
  frontend/public/apple-icon-57x57.png
  frontend/public/apple-icon-60x60.png
  frontend/public/apple-icon-72x72.png
  frontend/public/apple-icon-76x76.png
  frontend/public/apple-icon-precomposed.png
  frontend/public/apple-icon.png
  frontend/public/browserconfig.xml
  frontend/public/favicon-16x16.png
  frontend/public/favicon-32x32.png
  frontend/public/favicon-96x96.png
  frontend/public/favicon.ico
  frontend/public/manifest.json
  frontend/public/ms-icon-144x144.png
  frontend/public/ms-icon-150x150.png
  frontend/public/ms-icon-310x310.png
  frontend/public/ms-icon-70x70.png
  frontend/public/vercel.svg
  frontend/src/components/common/FaviconConfig/index.tsx
  frontend/src/components/common/GroupArticleCard/index.tsx
  frontend/src/components/common/HeadMeta/index.tsx
  frontend/src/components/common/Header/UserLoginItem/index.tsx
  frontend/src/hooks/queries/useFetchMyArticle.ts
  frontend/src/hooks/queries/useLogout.ts
  frontend/src/pages/_document.tsx
Labels: 💎 프론트엔드, ✨ feature

#288 [Feature] Group Application - 참가 취소 API Test
  backend/test/group-application.e2e-spec.ts
Labels: ✍ 리뷰요청, 🌿 백엔드, ✨ feature

#276 [Feature] CI/CD 최적화
  .github/workflows/backend-dev-cd.yml
  .github/workflows/backend-dev-ci.yml
  .github/workflows/frontend-cd.yml
  .github/workflows/frontend-ci.yml
  .github/workflows/slack-notification.yml
  backend/Dockerfile
  frontend/Dockerfile
  frontend/Dockerfile.development
Labels: 🌿 백엔드, ✨ feature, 🚀 Deploy

#297 [Feature] heic, heif 업로드 지원
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/article/ArticlePostInput/index.tsx
  frontend/src/components/article/ImageThumbnail/index.tsx
  frontend/src/hooks/useImageUpload.ts
  frontend/src/utils/uploadImage.ts
Labels: 💎 프론트엔드, ✨ feature

#295 [BUGFIX] repository 설정 변경
  backend/src/app/group-application/group-application.repository.ts
  backend/src/app/group-article/group-article.module.ts
  backend/src/app/group-article/repository/group-category.repository.ts
  backend/src/app/group-article/repository/group.repository.ts
  backend/src/app/user/user.repository.ts
Labels: 🐞 BugFix, 🌿 백엔드

#298 [Feature] Group Application - 내가 참여한 모임 조회 API Test
  backend/test/group-application.e2e-spec.ts
Labels: ✍ 리뷰요청, 🌿 백엔드, ✨ feature

#303 [Feature] 댓글 추가시 상단에 추가된 댓글 표시
  frontend/src/components/article/Comment/index.tsx
  frontend/src/components/article/CommentInput/CommentInput.stories.tsx
  frontend/src/components/article/CommentInput/index.tsx
  frontend/src/hooks/queries/useAddComment.ts
  frontend/src/hooks/queries/useDeleteComment.ts
  frontend/src/hooks/queries/useFetchComments.ts
  frontend/src/pages/article/[id].tsx
  frontend/src/typings/types.ts
Labels: 💎 프론트엔드, ✨ feature

#322 [Feature] 로딩중 스켈레톤 적용
  frontend/src/components/common/NotificationLoading/NotificationLoading.tsx
  frontend/src/components/common/ProfileLoading/ProfileLoading.tsx
  frontend/src/hooks/queries/useFetchNotifications.ts
  frontend/src/pages/article/edit/[id].tsx
  frontend/src/pages/notification.tsx
  frontend/src/pages/user/[id].tsx
Labels: 💎 프론트엔드, ✨ feature

#300 [Feature] 메인페이지 스크롤 복구, 필터 유지
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/common/ScrollHandler/index.tsx
  frontend/src/pages/_app.tsx
  frontend/src/pages/index.tsx
  frontend/src/recoil/atoms.ts
  frontend/tsconfig.json
Labels: 💎 프론트엔드, ✨ feature

#318 [Feature] 다른 브라우저로 접속시 경고메시지 제공
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/common/BrowserCheck/index.tsx
  frontend/src/pages/_app.tsx
  frontend/src/pages/my/edit.tsx
Labels: 💎 프론트엔드, ✨ feature

#329 [Feature] 환경에 따른 CORS, Swagger 처리
  backend/src/main.ts
  backend/src/setNestApp.ts
  backend/src/setSwagger.ts
Labels: 🌿 백엔드, ✨ feature

#323 [BUGFIX] 게시글 로드시 댓글이 먼저보이는 현상
  frontend/src/pages/article/[id].tsx
Labels: 🐞 BugFix, 💎 프론트엔드

#332 [Feature]페이지네이션 방식 변경사항 반영
  frontend/src/components/common/BrowserCheck/index.tsx
  frontend/src/hooks/queries/useFetchGroupArticles.ts
  frontend/src/pages/_app.tsx
  frontend/src/pages/index.tsx
Labels: 💎 프론트엔드, ✨ feature, 🚨 우선순위-긴급

#334 [Feature] 이미지 프리로드, 댓글 삭제시 추가된 댓글 안보이게 수정
  frontend/src/components/common/GroupArticleCard/index.tsx
  frontend/src/pages/article/[id].tsx
Labels: 💎 프론트엔드, ✨ feature

#336 [BUGFIX] 사파리 알림 컴포넌트 깨짐 현상
  frontend/src/components/notification/NotificationItem/NotificationItem.stories.tsx
  frontend/src/components/notification/NotificationItem/index.tsx
Labels: 🐞 BugFix, 💎 프론트엔드, 🚨 우선순위-긴급
