Repository boostcampwm-2022/web13-moyeomoyeo, pull requests merged in 2023-01, with the labels that each got.

#342 [Feature] 알림 SSE 적용 및 NoOffset 페이지네이션 적용하기
  backend/local/nginx.conf
  backend/nginx/dev/conf/nginx.conf
  backend/nginx/prod/nginx.conf
  backend/package.json
  backend/src/app.controller.spec.ts
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/app.service.ts
  backend/src/app/group-article/group-article.controller.ts
  backend/src/app/notification/dto/notification-sse.dto.ts
  backend/src/app/notification/dto/v2-get-user-notifications-response.dto.ts
  backend/src/app/notification/entity/notification.entity.ts
  backend/src/app/notification/notification.controller.ts
  backend/src/app/notification/notification.listener.ts
  backend/src/app/notification/notification.module.ts
  backend/src/app/notification/repository/user-notification.repository.ts
  backend/src/common/module/sse/sse-type.ts
  backend/src/common/module/sse/sse.module.ts
  backend/src/common/module/sse/sse.service.ts
  backend/src/sse.controller.ts
  backend/test/app.e2e-spec.ts
Labels: 🌿 백엔드, ✨ feature

#341 [Feature] Group Article API Test 코드 작성
  backend/src/app/group-article/dto/group-article-register-request.dto.ts
  backend/test/group-article.e2e-spec.ts
Labels: 🌿 백엔드, ✨ feature, 🛠 리팩토링

#345 [Feature] SSE 알림 적용
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/common/NotificationToast/index.tsx
  frontend/src/components/notification/NotificationItem/index.tsx
  frontend/src/hooks/queries/useFetchNotifications.ts
  frontend/src/hooks/useNotificationEvent.ts
  frontend/src/pages/_app.tsx
Labels: 💎 프론트엔드, ✨ feature

#348 [Feature] Modal 로직 리팩토링
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/article/ArticleComments/index.tsx
  frontend/src/components/article/Comment/index.tsx
  frontend/src/components/article/MenuButton/index.tsx
  frontend/src/components/article/ParticipateButton/ApplyButton/index.tsx
  frontend/src/components/article/ParticipateButton/CancelButton/index.tsx
  frontend/src/components/common/Header/UserLoginItem/index.tsx
  frontend/src/components/common/Modals/index.tsx
  frontend/src/components/notification/NotificationItem/index.tsx
  frontend/src/hooks/useModals.ts
  frontend/src/pages/_app.tsx
  frontend/src/pages/article/[id].tsx
  frontend/src/pages/article/write/index.tsx
  frontend/src/recoil/atoms.ts
Labels: 💎 프론트엔드, 🛠 리팩토링
